Feat/logo
cloud-native-austria/kcd-austria-website pull request #10
Opened 2024-03-05 12:22 UTC by KatharinaSick

![image](https://github.com/cloud-native-austria/kcd-austria-website/assets/9420018/286bd22d-dfa4-4690-8eec-b8a150b79eee)

2024-03-11 22:16 UTC, jgrumboe requested changes

2024-03-11 22:16 UTC, jgrumboe commented on src/components/pages/team/team/team.jsx
> +    name: 'Thomas Schütz',
Don't merge this change, please. Thomas last name is written like this and he committed it like this on his own (see file history).

2024-03-12 07:48 UTC, KatharinaSick commented on src/components/pages/team/team/team.jsx
> +    name: 'Thomas Schütz',
Sorry and thank you for checking! Somehow I thought he changed it the other way round and that I overwrote it with my accidental push to main a while back 🙈

2024-03-12 11:04 UTC, jgrumboe approved these changes

2024-03-12 11:05 UTC, merged