Add-workshops-to-ticket-section
cloud-native-austria/kcd-austria-website pull request #48
Opened 2024-08-02 06:27 UTC by jgrumboe

2024-08-02 11:48 UTC, jgrumboe commented
I'm just thinking:
Can/Should we present the workshops already in some kind of table format? Like "Room 1" / "Room 2" as columns and "Morning"/"Afternoon" as rows?
I'd like to make it clear to people that they will pay 120€ and pick a combination of one morning and one afternoon workshop (with lunch included).

2024-08-02 12:39 UTC, holistic-developer requested changes

2024-08-02 12:39 UTC, holistic-developer commented on src/components/pages/home/speakers/SpeakerProfileImage.jsx
> +    if (!speaker) return ""
in this case we could show a fallback image

2024-08-02 12:39 UTC, holistic-developer commented on src/components/pages/home/speakers/SpeakerProfileImage.jsx
> +    const speaker = speakers.find(speaker => speaker.id === speakerId || speaker.firstName === firstName);
I would only keep the check for the id and remove the error prone comparison by first name

2024-08-02 12:41 UTC, holistic-developer commented
> I'm just thinking:
> Can/Should we present the workshops already in some kind of table format? Like "Room 1" / "Room 2" as columns and "Morning"/"Afternoon" as rows?
> I'd like to make it clear to people that they will pay 120€ and pick a combination of one morning and one afternoon workshop (with lunch included).

You are right, this should be absolutely clear.
I tried a tabular layout, but it would not work on mobile.
I thought of adding small pills to indicate the time slots of the workshops.

2024-08-02 13:54 UTC, jgrumboe commented on src/components/pages/home/speakers/SpeakerProfileImage.jsx
> +    const speaker = speakers.find(speaker => speaker.id === speakerId || speaker.firstName === firstName);
Yes, I had the id first. And thinking it through for four speakers it's not much effort to get the id from sessionize.

2024-08-02 13:55 UTC, jgrumboe commented
> You are right, this should be absolutely clear. I tried a tabular layout, but it would not work on mobile. I thought of adding small pills to indicate the time slots of the workshops.

Yeah, we have these small pills anyway here and there, good idea, it would fit into the overall layout.

2024-08-05 06:27 UTC, jgrumboe commented on src/components/pages/home/speakers/SpeakerProfileImage.jsx
> +    const speaker = speakers.find(speaker => speaker.id === speakerId || speaker.firstName === firstName);
removed firstname

2024-08-05 07:40 UTC, jgrumboe commented on src/components/pages/home/speakers/SpeakerProfileImage.jsx
> +    if (!speaker) return ""
Added

2024-08-05 07:47 UTC, holistic-developer commented
I can check today if I can fix the alignment

2024-08-05 09:48 UTC, jgrumboe commented
> I can check today if I can fix the alignment

Thank you!
I just added a commit with modals for speaker and session details. It's not perfect, so maybe you should adjust the design a bit.

Overall, it would be great to merge it tonight to start workshop sale tomorrow.

2024-08-05 10:13 UTC, jgrumboe commented
> I just added a commit with modals for speaker and session details. It's not perfect, so maybe you should adjust the design a bit.

The modals look very bad on mobile 😢

2024-08-05 11:10 UTC, holistic-developer commented on src/components/pages/home/tickets/tickets.jsx
> +          </div>
```suggestion
          <div className="pl-10 flex flex-col content-between gap-1 h-full">
            <strong className="text-sm text-start bg-pink text-white py-1 px-2 rounded-full inline-block self-start">Room 2, 13:00-16:00</strong>
            <div className="flex flex-col gap-1 items-start text-start justify-center h-full">
              <h4 className="text-purple font-bold text-balance">Kubernetes Performance Tuning</h4>
              <strong>Ant(on) Weiss</strong>
              <span className="text-balance text-gray-5 text-sm">Software Delivery Futurist</span>
            </div>
          </div>
```
This would align the pill left with the text but on top of the card
![image](https://github.com/user-attachments/assets/9f77242c-db8b-4268-bc6f-9c59e9ece43d)

2024-08-05 12:26 UTC, jgrumboe commented
@holistic-developer Thanks, I've adjusted according to your feedback.

2024-08-05 12:47 UTC, holistic-developer approved these changes

2024-08-05 19:21 UTC, merged